// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/rpc/admin.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PcId          string                 `protobuf:"bytes,2,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	Minutes       int32                  `protobuf:"varint,3,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRequest) Reset() {
	*x = GrantRequest{}
	mi := &file_pkg_rpc_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRequest) ProtoMessage() {}

func (x *GrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRequest.ProtoReflect.Descriptor instead.
func (*GrantRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_proto_rawDescGZIP(), []int{0}
}

func (x *GrantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GrantRequest) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

func (x *GrantRequest) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcId          string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_pkg_rpc_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_proto_rawDescGZIP(), []int{1}
}

func (x *RevokeRequest) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_rpc_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_rpc_admin_proto protoreflect.FileDescriptor

const file_pkg_rpc_admin_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/rpc/admin.proto\x12\x03rpc\"V\n" +
	"\fGrantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x13\n" +
	"\x05pc_id\x18\x02 \x01(\tR\x04pcId\x12\x18\n" +
	"\aminutes\x18\x03 \x01(\x05R\aminutes\"$\n" +
	"\rRevokeRequest\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2r\n" +
	"\fAdminService\x12/\n" +
	"\vGrantAccess\x12\x11.rpc.GrantRequest\x1a\r.rpc.Response\x121\n" +
	"\fRevokeAccess\x12\x12.rpc.RevokeRequest\x1a\r.rpc.ResponseB%Z#github.com/Glack134/pc_club/pkg/rpcb\x06proto3"

var (
	file_pkg_rpc_admin_proto_rawDescOnce sync.Once
	file_pkg_rpc_admin_proto_rawDescData []byte
)

func file_pkg_rpc_admin_proto_rawDescGZIP() []byte {
	file_pkg_rpc_admin_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_admin_proto_rawDesc), len(file_pkg_rpc_admin_proto_rawDesc)))
	})
	return file_pkg_rpc_admin_proto_rawDescData
}

var file_pkg_rpc_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_rpc_admin_proto_goTypes = []any{
	(*GrantRequest)(nil),  // 0: rpc.GrantRequest
	(*RevokeRequest)(nil), // 1: rpc.RevokeRequest
	(*Response)(nil),      // 2: rpc.Response
}
var file_pkg_rpc_admin_proto_depIdxs = []int32{
	0, // 0: rpc.AdminService.GrantAccess:input_type -> rpc.GrantRequest
	1, // 1: rpc.AdminService.RevokeAccess:input_type -> rpc.RevokeRequest
	2, // 2: rpc.AdminService.GrantAccess:output_type -> rpc.Response
	2, // 3: rpc.AdminService.RevokeAccess:output_type -> rpc.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_rpc_admin_proto_init() }
func file_pkg_rpc_admin_proto_init() {
	if File_pkg_rpc_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_admin_proto_rawDesc), len(file_pkg_rpc_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_admin_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_admin_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_admin_proto_msgTypes,
	}.Build()
	File_pkg_rpc_admin_proto = out.File
	file_pkg_rpc_admin_proto_goTypes = nil
	file_pkg_rpc_admin_proto_depIdxs = nil
}
