// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/rpc/admin/admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_GetPcStatus_FullMethodName  = "/admin.AdminService/GetPcStatus"
	AdminService_LockPc_FullMethodName       = "/admin.AdminService/LockPc"
	AdminService_UnlockPc_FullMethodName     = "/admin.AdminService/UnlockPc"
	AdminService_StartProgram_FullMethodName = "/admin.AdminService/StartProgram"
	AdminService_StopProgram_FullMethodName  = "/admin.AdminService/StopProgram"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	GetPcStatus(ctx context.Context, in *PcStatusRequest, opts ...grpc.CallOption) (*PcStatusResponse, error)
	LockPc(ctx context.Context, in *LockPcRequest, opts ...grpc.CallOption) (*LockPcResponse, error)
	UnlockPc(ctx context.Context, in *UnlockPcRequest, opts ...grpc.CallOption) (*UnlockPcResponse, error)
	StartProgram(ctx context.Context, in *StartProgramRequest, opts ...grpc.CallOption) (*StartProgramResponse, error)
	StopProgram(ctx context.Context, in *StopProgramRequest, opts ...grpc.CallOption) (*StopProgramResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetPcStatus(ctx context.Context, in *PcStatusRequest, opts ...grpc.CallOption) (*PcStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PcStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_GetPcStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) LockPc(ctx context.Context, in *LockPcRequest, opts ...grpc.CallOption) (*LockPcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockPcResponse)
	err := c.cc.Invoke(ctx, AdminService_LockPc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UnlockPc(ctx context.Context, in *UnlockPcRequest, opts ...grpc.CallOption) (*UnlockPcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockPcResponse)
	err := c.cc.Invoke(ctx, AdminService_UnlockPc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StartProgram(ctx context.Context, in *StartProgramRequest, opts ...grpc.CallOption) (*StartProgramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartProgramResponse)
	err := c.cc.Invoke(ctx, AdminService_StartProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StopProgram(ctx context.Context, in *StopProgramRequest, opts ...grpc.CallOption) (*StopProgramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopProgramResponse)
	err := c.cc.Invoke(ctx, AdminService_StopProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	GetPcStatus(context.Context, *PcStatusRequest) (*PcStatusResponse, error)
	LockPc(context.Context, *LockPcRequest) (*LockPcResponse, error)
	UnlockPc(context.Context, *UnlockPcRequest) (*UnlockPcResponse, error)
	StartProgram(context.Context, *StartProgramRequest) (*StartProgramResponse, error)
	StopProgram(context.Context, *StopProgramRequest) (*StopProgramResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetPcStatus(context.Context, *PcStatusRequest) (*PcStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPcStatus not implemented")
}
func (UnimplementedAdminServiceServer) LockPc(context.Context, *LockPcRequest) (*LockPcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockPc not implemented")
}
func (UnimplementedAdminServiceServer) UnlockPc(context.Context, *UnlockPcRequest) (*UnlockPcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockPc not implemented")
}
func (UnimplementedAdminServiceServer) StartProgram(context.Context, *StartProgramRequest) (*StartProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProgram not implemented")
}
func (UnimplementedAdminServiceServer) StopProgram(context.Context, *StopProgramRequest) (*StopProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopProgram not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetPcStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PcStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetPcStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetPcStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetPcStatus(ctx, req.(*PcStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_LockPc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockPcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).LockPc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_LockPc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).LockPc(ctx, req.(*LockPcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UnlockPc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockPcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UnlockPc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UnlockPc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UnlockPc(ctx, req.(*UnlockPcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StartProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StartProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_StartProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StartProgram(ctx, req.(*StartProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StopProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StopProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_StopProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StopProgram(ctx, req.(*StopProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPcStatus",
			Handler:    _AdminService_GetPcStatus_Handler,
		},
		{
			MethodName: "LockPc",
			Handler:    _AdminService_LockPc_Handler,
		},
		{
			MethodName: "UnlockPc",
			Handler:    _AdminService_UnlockPc_Handler,
		},
		{
			MethodName: "StartProgram",
			Handler:    _AdminService_StartProgram_Handler,
		},
		{
			MethodName: "StopProgram",
			Handler:    _AdminService_StopProgram_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/rpc/admin/admin.proto",
}
