// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/rpc/admin/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PcStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcId          string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PcStatusRequest) Reset() {
	*x = PcStatusRequest{}
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PcStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcStatusRequest) ProtoMessage() {}

func (x *PcStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcStatusRequest.ProtoReflect.Descriptor instead.
func (*PcStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *PcStatusRequest) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

type PcStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PcId            string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	IsLocked        bool                   `protobuf:"varint,2,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	CpuUsage        float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage        float64                `protobuf:"fixed64,4,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	RunningPrograms []string               `protobuf:"bytes,5,rep,name=running_programs,json=runningPrograms,proto3" json:"running_programs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PcStatusResponse) Reset() {
	*x = PcStatusResponse{}
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PcStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcStatusResponse) ProtoMessage() {}

func (x *PcStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcStatusResponse.ProtoReflect.Descriptor instead.
func (*PcStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *PcStatusResponse) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

func (x *PcStatusResponse) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *PcStatusResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *PcStatusResponse) GetRamUsage() float64 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *PcStatusResponse) GetRunningPrograms() []string {
	if x != nil {
		return x.RunningPrograms
	}
	return nil
}

type LockPcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcId          string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockPcRequest) Reset() {
	*x = LockPcRequest{}
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockPcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockPcRequest) ProtoMessage() {}

func (x *LockPcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockPcRequest.ProtoReflect.Descriptor instead.
func (*LockPcRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *LockPcRequest) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

type LockPcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockPcResponse) Reset() {
	*x = LockPcResponse{}
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockPcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockPcResponse) ProtoMessage() {}

func (x *LockPcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockPcResponse.ProtoReflect.Descriptor instead.
func (*LockPcResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *LockPcResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnlockPcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcId          string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	AdminToken    string                 `protobuf:"bytes,2,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockPcRequest) Reset() {
	*x = UnlockPcRequest{}
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockPcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockPcRequest) ProtoMessage() {}

func (x *UnlockPcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockPcRequest.ProtoReflect.Descriptor instead.
func (*UnlockPcRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UnlockPcRequest) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

func (x *UnlockPcRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

type UnlockPcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockPcResponse) Reset() {
	*x = UnlockPcResponse{}
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockPcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockPcResponse) ProtoMessage() {}

func (x *UnlockPcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockPcResponse.ProtoReflect.Descriptor instead.
func (*UnlockPcResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_admin_proto_rawDescGZIP(), []int{5}
}

func (x *UnlockPcResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StartProgramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcId          string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	ProgramPath   string                 `protobuf:"bytes,2,opt,name=program_path,json=programPath,proto3" json:"program_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProgramRequest) Reset() {
	*x = StartProgramRequest{}
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProgramRequest) ProtoMessage() {}

func (x *StartProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProgramRequest.ProtoReflect.Descriptor instead.
func (*StartProgramRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_admin_proto_rawDescGZIP(), []int{6}
}

func (x *StartProgramRequest) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

func (x *StartProgramRequest) GetProgramPath() string {
	if x != nil {
		return x.ProgramPath
	}
	return ""
}

type StartProgramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProgramResponse) Reset() {
	*x = StartProgramResponse{}
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProgramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProgramResponse) ProtoMessage() {}

func (x *StartProgramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProgramResponse.ProtoReflect.Descriptor instead.
func (*StartProgramResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_admin_proto_rawDescGZIP(), []int{7}
}

func (x *StartProgramResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StopProgramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcId          string                 `protobuf:"bytes,1,opt,name=pc_id,json=pcId,proto3" json:"pc_id,omitempty"`
	ProgramName   string                 `protobuf:"bytes,2,opt,name=program_name,json=programName,proto3" json:"program_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProgramRequest) Reset() {
	*x = StopProgramRequest{}
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProgramRequest) ProtoMessage() {}

func (x *StopProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProgramRequest.ProtoReflect.Descriptor instead.
func (*StopProgramRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_admin_proto_rawDescGZIP(), []int{8}
}

func (x *StopProgramRequest) GetPcId() string {
	if x != nil {
		return x.PcId
	}
	return ""
}

func (x *StopProgramRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

type StopProgramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProgramResponse) Reset() {
	*x = StopProgramResponse{}
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProgramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProgramResponse) ProtoMessage() {}

func (x *StopProgramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_admin_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProgramResponse.ProtoReflect.Descriptor instead.
func (*StopProgramResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_admin_admin_proto_rawDescGZIP(), []int{9}
}

func (x *StopProgramResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_rpc_admin_admin_proto protoreflect.FileDescriptor

const file_pkg_rpc_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/rpc/admin/admin.proto\x12\x05admin\"&\n" +
	"\x0fPcStatusRequest\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId\"\xa9\x01\n" +
	"\x10PcStatusResponse\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId\x12\x1b\n" +
	"\tis_locked\x18\x02 \x01(\bR\bisLocked\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x04 \x01(\x01R\bramUsage\x12)\n" +
	"\x10running_programs\x18\x05 \x03(\tR\x0frunningPrograms\"$\n" +
	"\rLockPcRequest\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId\"*\n" +
	"\x0eLockPcResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"G\n" +
	"\x0fUnlockPcRequest\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId\x12\x1f\n" +
	"\vadmin_token\x18\x02 \x01(\tR\n" +
	"adminToken\",\n" +
	"\x10UnlockPcResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x13StartProgramRequest\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId\x12!\n" +
	"\fprogram_path\x18\x02 \x01(\tR\vprogramPath\"0\n" +
	"\x14StartProgramResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"L\n" +
	"\x12StopProgramRequest\x12\x13\n" +
	"\x05pc_id\x18\x01 \x01(\tR\x04pcId\x12!\n" +
	"\fprogram_name\x18\x02 \x01(\tR\vprogramName\"/\n" +
	"\x13StopProgramResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd1\x02\n" +
	"\fAdminService\x12>\n" +
	"\vGetPcStatus\x12\x16.admin.PcStatusRequest\x1a\x17.admin.PcStatusResponse\x125\n" +
	"\x06LockPc\x12\x14.admin.LockPcRequest\x1a\x15.admin.LockPcResponse\x12;\n" +
	"\bUnlockPc\x12\x16.admin.UnlockPcRequest\x1a\x17.admin.UnlockPcResponse\x12G\n" +
	"\fStartProgram\x12\x1a.admin.StartProgramRequest\x1a\x1b.admin.StartProgramResponse\x12D\n" +
	"\vStopProgram\x12\x19.admin.StopProgramRequest\x1a\x1a.admin.StopProgramResponseB\x1dZ\x1bpcclub-system/pkg/rpc/adminb\x06proto3"

var (
	file_pkg_rpc_admin_admin_proto_rawDescOnce sync.Once
	file_pkg_rpc_admin_admin_proto_rawDescData []byte
)

func file_pkg_rpc_admin_admin_proto_rawDescGZIP() []byte {
	file_pkg_rpc_admin_admin_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_admin_admin_proto_rawDesc), len(file_pkg_rpc_admin_admin_proto_rawDesc)))
	})
	return file_pkg_rpc_admin_admin_proto_rawDescData
}

var file_pkg_rpc_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_rpc_admin_admin_proto_goTypes = []any{
	(*PcStatusRequest)(nil),      // 0: admin.PcStatusRequest
	(*PcStatusResponse)(nil),     // 1: admin.PcStatusResponse
	(*LockPcRequest)(nil),        // 2: admin.LockPcRequest
	(*LockPcResponse)(nil),       // 3: admin.LockPcResponse
	(*UnlockPcRequest)(nil),      // 4: admin.UnlockPcRequest
	(*UnlockPcResponse)(nil),     // 5: admin.UnlockPcResponse
	(*StartProgramRequest)(nil),  // 6: admin.StartProgramRequest
	(*StartProgramResponse)(nil), // 7: admin.StartProgramResponse
	(*StopProgramRequest)(nil),   // 8: admin.StopProgramRequest
	(*StopProgramResponse)(nil),  // 9: admin.StopProgramResponse
}
var file_pkg_rpc_admin_admin_proto_depIdxs = []int32{
	0, // 0: admin.AdminService.GetPcStatus:input_type -> admin.PcStatusRequest
	2, // 1: admin.AdminService.LockPc:input_type -> admin.LockPcRequest
	4, // 2: admin.AdminService.UnlockPc:input_type -> admin.UnlockPcRequest
	6, // 3: admin.AdminService.StartProgram:input_type -> admin.StartProgramRequest
	8, // 4: admin.AdminService.StopProgram:input_type -> admin.StopProgramRequest
	1, // 5: admin.AdminService.GetPcStatus:output_type -> admin.PcStatusResponse
	3, // 6: admin.AdminService.LockPc:output_type -> admin.LockPcResponse
	5, // 7: admin.AdminService.UnlockPc:output_type -> admin.UnlockPcResponse
	7, // 8: admin.AdminService.StartProgram:output_type -> admin.StartProgramResponse
	9, // 9: admin.AdminService.StopProgram:output_type -> admin.StopProgramResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_rpc_admin_admin_proto_init() }
func file_pkg_rpc_admin_admin_proto_init() {
	if File_pkg_rpc_admin_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_admin_admin_proto_rawDesc), len(file_pkg_rpc_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_admin_admin_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_admin_admin_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_admin_admin_proto_msgTypes,
	}.Build()
	File_pkg_rpc_admin_admin_proto = out.File
	file_pkg_rpc_admin_admin_proto_goTypes = nil
	file_pkg_rpc_admin_admin_proto_depIdxs = nil
}
